server:
  port: 8089


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: thread-study

mybatis:
  mapper-locations: classpath:/com.gxd.hystrix/*Mapper.xml

#logging.config: classpath:logback.xml